# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4_RExDIM-SwLE3u-ohp1m6WvdoiSEyu
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("اختبار بسيط")
st.write("إذا ظهرت هذه الرسالة، الكود يعمل بنجاح!")

# 1. تعريف الكلاس (المنطق)
class BreadfastAnalytics:
    def __init__(self, df):
        self.df = df.copy()
        self._preprocess()

    def _preprocess(self):
        # تنظيف الأعمدة
        self.df.columns = self.df.columns.str.strip()
        # تحويل أنواع البيانات
        self.df['Price (EGP)'] = pd.to_numeric(self.df['Price (EGP)'], errors='coerce').fillna(0)
        self.df['Quantity'] = pd.to_numeric(self.df['Quantity'], errors='coerce').fillna(0)
        self.df['Total_Order_Value'] = self.df['Price (EGP)'] * self.df['Quantity']
        self.df['Order_Time'] = pd.to_datetime(self.df['Order_Time'], format='%H:%M', errors='coerce').dt.time

# 2. إعدادات الصفحة
st.set_page_config(page_title="Breadfast Operations", layout="wide")
st.title("📊 Breadfast Operations Intelligence")
st.write("ارفع ملف الطلبات اليومي للحصول على الـ KPIs والتقارير.")

# 3. رفع الملف
uploaded_file = st.file_uploader("قم برفع ملف الطلبات (CSV)", type="csv")

if uploaded_file is not None:
    # معالجة البيانات
    df = pd.read_csv(uploaded_file)
    analysis = BreadfastAnalytics(df)
    data = analysis.df

    # KPIs Cards
    c1, c2, c3 = st.columns(3)
    c1.metric("إجمالي الإيرادات", f"{data['Total_Order_Value'].sum():,.0f} EGP")
    c2.metric("عدد الطلبات", int(data['Order_ID'].nunique()))
    c3.metric("متوسط قيمة الطلب", f"{data['Total_Order_Value'].mean():,.0f} EGP")

    # الرسوم البيانية
    st.subheader("تحليل الأداء")
    col_chart1, col_chart2 = st.columns(2)

    with col_chart1:
        fig = px.bar(data.groupby('Category')['Total_Order_Value'].sum().reset_index(),
                     x='Category', y='Total_Order_Value', title="الإيرادات حسب التصنيف", color='Category')
        st.plotly_chart(fig, use_container_width=True)

    with col_chart2:
        fig_prod = px.pie(data, values='Total_Order_Value', names='Product', title="توزيع مبيعات المنتجات")
        st.plotly_chart(fig_prod, use_container_width=True)

    # عرض الجدول
    with st.expander("عرض بيانات الطلبات"):
        st.dataframe(data)
else:
    st.info("بانتظار رفع ملف البيانات للبدء...")

